// Generated by scripts/generate_profile_deck_minion_cost_summon.py. Do not edit.
#include <Rosetta/PlayMode/CardSets/ManaMindProfileDeckMinionCostSummonGen.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/IncludeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FilterStackTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/RandomTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SummonStackTask.hpp>
#include <Rosetta/PlayMode/Triggers/Trigger.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
#include <vector>
namespace RosettaStone::PlayMode {
void ManaMindProfileDeckMinionCostSummonGen::AddAll(std::map<std::string, CardDef>& cards) {
    using namespace SimpleTasks;
    if (cards.contains("JAIL_327")) throw std::logic_error("duplicate generated CardDef: JAIL_327");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<IncludeTask>(EntityType::DECK),
            std::make_shared<FilterStackTask>(std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsMinion()), std::make_shared<SelfCondition>(SelfCondition::IsCost(2, RelaSign::LEQ))}),
            std::make_shared<RandomTask>(EntityType::STACK, 1),
            std::make_shared<SummonStackTask>(true),
        };
        cardDef.power.GetTrigger()->lastTurn = 3;
        cards.emplace("JAIL_327", std::move(cardDef));
    }

    if (cards.contains("JAIL_516")) throw std::logic_error("duplicate generated CardDef: JAIL_516");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::DECK));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsMinion()), std::make_shared<SelfCondition>(SelfCondition::IsCost(2, RelaSign::LEQ))}));
        cardDef.power.AddPowerTask(std::make_shared<RandomTask>(EntityType::STACK, 2));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ULD_178a4", EntityType::STACK));
        cardDef.power.AddPowerTask(std::make_shared<SummonStackTask>(true));
        cards.emplace("JAIL_516", std::move(cardDef));
    }
}
}
