// Generated by scripts/generate_keyword_only_cards.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindKeywordOnlyCardsGen.hpp>
#include <stdexcept>
namespace RosettaStone::PlayMode {
void ManaMindKeywordOnlyCardsGen::AddAll(std::map<std::string, CardDef>& cards) {
    if (cards.contains("CORE_GIL_558")) throw std::logic_error("duplicate generated CardDef: CORE_GIL_558");
    CardDef cardDef_CORE_GIL_558;
    cardDef_CORE_GIL_558.ClearData();
    cardDef_CORE_GIL_558.power.AddPowerTask(nullptr);
    cards.emplace("CORE_GIL_558", cardDef_CORE_GIL_558);
    if (cards.contains("CORE_ULD_723")) throw std::logic_error("duplicate generated CardDef: CORE_ULD_723");
    CardDef cardDef_CORE_ULD_723;
    cardDef_CORE_ULD_723.ClearData();
    cardDef_CORE_ULD_723.power.AddPowerTask(nullptr);
    cards.emplace("CORE_ULD_723", cardDef_CORE_ULD_723);
    if (cards.contains("EDR_486")) throw std::logic_error("duplicate generated CardDef: EDR_486");
    CardDef cardDef_EDR_486;
    cardDef_EDR_486.ClearData();
    cardDef_EDR_486.power.AddPowerTask(nullptr);
    cards.emplace("EDR_486", cardDef_EDR_486);
    if (cards.contains("END_031")) throw std::logic_error("duplicate generated CardDef: END_031");
    CardDef cardDef_END_031;
    cardDef_END_031.ClearData();
    cardDef_END_031.power.AddPowerTask(nullptr);
    cards.emplace("END_031", cardDef_END_031);
    if (cards.contains("RLK_067")) throw std::logic_error("duplicate generated CardDef: RLK_067");
    CardDef cardDef_RLK_067;
    cardDef_RLK_067.ClearData();
    cardDef_RLK_067.power.AddPowerTask(nullptr);
    cards.emplace("RLK_067", cardDef_RLK_067);
    if (cards.contains("CORE_EX1_250")) throw std::logic_error("duplicate generated CardDef: CORE_EX1_250");
    CardDef cardDef_CORE_EX1_250;
    cardDef_CORE_EX1_250.ClearData();
    cardDef_CORE_EX1_250.power.AddPowerTask(nullptr);
    cards.emplace("CORE_EX1_250", cardDef_CORE_EX1_250);
}
}  // namespace RosettaStone::PlayMode
