// Generated by scripts/generate_core_card_aliases.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindCoreAliasCardsGen.hpp>

#include <array>
#include <stdexcept>
#include <string_view>

namespace RosettaStone::PlayMode
{
void ManaMindCoreAliasCardsGen::AddAll(std::map<std::string, CardDef>& cards)
{
    struct Alias { std::string_view current; std::string_view base; };
    static constexpr Alias aliases[] = {
        Alias{ "CORE_BAR_801", "BAR_801" },
        Alias{ "CORE_SW_108", "SW_108" },
        Alias{ "CORE_BT_072", "BT_072" },
        Alias{ "CORE_BAR_310", "BAR_310" },
        Alias{ "CORE_AV_337", "AV_337" },
        Alias{ "CORE_BAR_541", "BAR_541" },
        Alias{ "CORE_KAR_062", "KAR_062" },
        Alias{ "CORE_BT_156", "BT_156" },
        Alias{ "CORE_SW_068", "SW_068" },
        Alias{ "CORE_SW_088", "SW_088" },
        Alias{ "CORE_EX1_131", "EX1_131" },
        Alias{ "CORE_EX1_278", "EX1_278" },
        Alias{ "CORE_DRG_107", "DRG_107" },
        Alias{ "CORE_WC_701", "WC_701" },
        Alias{ "CORE_BT_701", "BT_701" },
        Alias{ "CORE_BAR_313", "BAR_313" },
        Alias{ "CORE_EX1_058", "EX1_058" },
        Alias{ "CORE_ONY_018", "ONY_018" },
        Alias{ "CORE_SW_439", "SW_439" },
        Alias{ "CORE_TSC_650", "TSC_650" },
        Alias{ "CORE_ULD_133", "ULD_133" },
        Alias{ "CORE_BAR_812", "BAR_812" },
        Alias{ "CORE_BAR_878", "BAR_878" },
        Alias{ "CORE_BT_510", "BT_510" },
        Alias{ "CORE_EX1_559", "EX1_559" },
        Alias{ "CORE_WC_042", "WC_042" },
        Alias{ "CORE_BT_120", "BT_120" },
        Alias{ "CORE_BT_321", "BT_321" },
        Alias{ "CORE_BT_493", "BT_493" },
        Alias{ "CORE_DAL_575", "DAL_575" },
        Alias{ "CORE_DAL_720", "DAL_720" },
        Alias{ "CORE_DRG_024", "DRG_024" },
        Alias{ "CORE_EX1_100", "EX1_100" },
        Alias{ "CORE_KAR_057", "KAR_057" },
        Alias{ "CORE_ONY_022", "ONY_022" },
        Alias{ "CORE_REV_308", "REV_308" },
        Alias{ "CORE_SCH_717", "SCH_717" },
        Alias{ "CORE_ULD_152", "ULD_152" },
        Alias{ "CORE_ULD_165", "ULD_165" },
        Alias{ "CORE_ULD_280", "ULD_280" },
        Alias{ "CORE_BT_292", "BT_292" },
        Alias{ "CORE_DRG_256", "DRG_256" },
        Alias{ "CORE_EX1_014", "EX1_014" },
        Alias{ "CORE_EX1_189", "EX1_189" },
        Alias{ "CORE_EX1_198", "EX1_198" },
        Alias{ "CORE_EX1_310", "EX1_310" },
        Alias{ "CORE_KAR_077", "KAR_077" },
        Alias{ "CORE_NEW1_022", "NEW1_022" },
        Alias{ "CORE_SCH_713", "SCH_713" },
        Alias{ "CORE_SW_072", "SW_072" },
        Alias{ "CORE_SW_429", "SW_429" },
        Alias{ "CORE_TRL_111", "TRL_111" },
        Alias{ "CORE_ULD_178", "ULD_178" },
        Alias{ "CORE_UNG_809", "UNG_809" },
        Alias{ "CORE_UNG_912", "UNG_912" },
        Alias{ "CORE_SW_442", "SW_442" },
        Alias{ "CORE_AT_052", "EX1_247" },
        Alias{ "CORE_WON_096", "LOE_023" },
        Alias{ "CORE_WON_337", "KAR_091" },
        Alias{ "Core_LOE_115", "LOE_115" },
        Alias{ "Core_UNG_072", "ULD_195" },
        Alias{ "TIME_603", "REV_251" },
        Alias{ "TIME_720", "ULD_189" },
        Alias{ "TLC_483", "ULD_309" },
        Alias{ "CORE_EX1_002", "EX1_002" },
    };

    for (const auto& alias : aliases)
    {
        if (cards.contains(std::string(alias.current)))
        {
            throw std::logic_error("duplicate generated Core CardDef: " + std::string(alias.current));
        }

        const auto base = cards.find(std::string(alias.base));
        if (base == cards.end())
        {
            throw std::logic_error("missing base CardDef for Core alias: " + std::string(alias.base));
        }

        const bool inserted = cards.emplace(std::string(alias.current), base->second).second;
        if (!inserted)
        {
            throw std::logic_error("failed to register generated Core CardDef: " + std::string(alias.current));
        }
    }
}
}  // namespace RosettaStone::PlayMode
