// Generated by scripts/generate_filtered_school_draw.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindFilteredSchoolDrawGen.hpp>
#include <Rosetta/PlayMode/Cards/CardPowers.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawSpellTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode
{
void ManaMindFilteredSchoolDrawGen::AddAll(std::map<std::string, CardDef>& cards)
{
using namespace SimpleTasks;

    if (cards.contains("FIR_929"))
        throw std::logic_error("duplicate generated CardDef: FIR_929");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawSpellTask>(SpellSchool::FIRE, 1));
        cards.emplace("FIR_929", std::move(cardDef));
    }

    if (cards.contains("RLK_511"))
        throw std::logic_error("duplicate generated CardDef: RLK_511");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawSpellTask>(SpellSchool::FROST, 1));
        cards.emplace("RLK_511", std::move(cardDef));
    }
}
}  // namespace RosettaStone::PlayMode
