// Generated by scripts/generate_held_card_gate_fixed_battlecry.py. Do not edit.
#include <Rosetta/PlayMode/CardSets/ManaMindHeldCardGateFixedBattlecryGen.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ConditionTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FlagTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/RefreshManaTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SetGameTagTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DamageTask.hpp>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode {
void ManaMindHeldCardGateFixedBattlecryGen::AddAll(std::map<std::string, CardDef>& cards) {
    using namespace SimpleTasks;
    if (cards.contains("CATA_111")) throw std::logic_error("duplicate generated CardDef: CATA_111");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(
            EntityType::SOURCE,
            std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsHoldingRace(Race::DRAGON))}));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{
                    std::make_shared<RefreshManaTask>(2)}));
        cards.emplace("CATA_111", std::move(cardDef));
    }

    if (cards.contains("CORE_RLK_814")) throw std::logic_error("duplicate generated CardDef: CORE_RLK_814");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(
            EntityType::SOURCE,
            std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsHoldingSpellSchool(SpellSchool::SHADOW))}));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{
                    std::make_shared<AddEnchantmentTask>("BRM_033e", EntityType::SOURCE)}));
        cards.emplace("CORE_RLK_814", std::move(cardDef));
    }

    if (cards.contains("EDR_472")) throw std::logic_error("duplicate generated CardDef: EDR_472");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.property.playReqs.emplace(PlayReq::REQ_TARGET_IF_AVAILABLE_AND_SPELL_COST_AT_LEAST_IN_HAND, 5);
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(
            EntityType::SOURCE,
            std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::HasSpellInHandWithCostAtLeast(5))}));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{
                    std::make_shared<DamageTask>(EntityType::TARGET, 3)}));
        cards.emplace("EDR_472", std::move(cardDef));
    }

    if (cards.contains("FIR_961")) throw std::logic_error("duplicate generated CardDef: FIR_961");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(
            EntityType::SOURCE,
            std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::HasSpellInHandWithCostAtLeast(5))}));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{
                    std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::DIVINE_SHIELD, 1),
                    std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::LIFESTEAL, 1)}));
        cards.emplace("FIR_961", std::move(cardDef));
    }

    if (cards.contains("TIME_062")) throw std::logic_error("duplicate generated CardDef: TIME_062");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(
            EntityType::SOURCE,
            std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsHoldingRace(Race::DRAGON))}));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{
                    std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::TAUNT, 1),
                    std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::DIVINE_SHIELD, 1)}));
        cards.emplace("TIME_062", std::move(cardDef));
    }
}
}
