// Generated by scripts/generate_metadata_only_cards.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindMetadataOnlyCardsGen.hpp>
#include <stdexcept>
namespace RosettaStone::PlayMode {
void ManaMindMetadataOnlyCardsGen::AddAll(std::map<std::string, CardDef>& cards) {
    if (cards.contains("Core_CS2_200")) throw std::logic_error("duplicate generated CardDef: Core_CS2_200");
    CardDef cardDef_Core_CS2_200;
    cardDef_Core_CS2_200.ClearData();
    cardDef_Core_CS2_200.power.AddPowerTask(nullptr);
    cards.emplace("Core_CS2_200", cardDef_Core_CS2_200);
    if (cards.contains("TIME_053")) throw std::logic_error("duplicate generated CardDef: TIME_053");
    CardDef cardDef_TIME_053;
    cardDef_TIME_053.ClearData();
    cardDef_TIME_053.power.AddPowerTask(nullptr);
    cards.emplace("TIME_053", cardDef_TIME_053);
    if (cards.contains("TLC_248")) throw std::logic_error("duplicate generated CardDef: TLC_248");
    CardDef cardDef_TLC_248;
    cardDef_TLC_248.ClearData();
    cardDef_TLC_248.power.AddPowerTask(nullptr);
    cards.emplace("TLC_248", cardDef_TLC_248);
}
}  // namespace RosettaStone::PlayMode
