// Generated by scripts/generate_after_attack_draw.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindAfterAttackDrawGen.hpp>
#include <Rosetta/PlayMode/Cards/CardPowers.hpp>
#include <Rosetta/PlayMode/Triggers/Trigger.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ArmorTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DamageTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode
{
void ManaMindAfterAttackDrawCardsGen::AddAll(std::map<std::string, CardDef>& cards)
{
using namespace SimpleTasks;

    if (cards.contains("CAP_003"))
        throw std::logic_error("duplicate generated CardDef: CAP_003");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::SELF;
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<DrawTask>(1),
        };
        cards.emplace("CAP_003", std::move(cardDef));
    }

    if (cards.contains("EDR_253"))
        throw std::logic_error("duplicate generated CardDef: EDR_253");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<DrawTask>(1),
        };
        cards.emplace("EDR_253", std::move(cardDef));
    }

    if (cards.contains("CORE_NX2_028"))
        throw std::logic_error("duplicate generated CardDef: CORE_NX2_028");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<ArmorTask>(4),
            std::make_shared<DrawTask>(1),
        };
        cards.emplace("CORE_NX2_028", std::move(cardDef));
    }

    if (cards.contains("TLC_478"))
        throw std::logic_error("duplicate generated CardDef: TLC_478");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<DamageTask>(EntityType::ALL_MINIONS_NOSOURCE, 1, false),
        };
        cards.emplace("TLC_478", std::move(cardDef));
    }

    if (cards.contains("TLC_840"))
        throw std::logic_error("duplicate generated CardDef: TLC_840");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::SELF;
        cardDef.power.GetTrigger()->tasks = {
            std::make_shared<DamageTask>(EntityType::ENEMY_HERO, 2, false),
        };
        cards.emplace("TLC_840", std::move(cardDef));
    }
}
}  // namespace RosettaStone::PlayMode
