// Generated by scripts/generate_effect_composition.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindEffectCompositionGen.hpp>
#include <Rosetta/PlayMode/Cards/CardPowers.hpp>
#include <Rosetta/PlayMode/Cards/Card.hpp>
#include <Rosetta/PlayMode/Models/Playable.hpp>
#include <Rosetta/PlayMode/Models/Player.hpp>
#include <Rosetta/PlayMode/Models/HeroPower.hpp>
#include <Rosetta/PlayMode/Zones/DeckZone.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Triggers/Trigger.hpp>

#include <Rosetta/PlayMode/Tasks/ITask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddCardTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ArmorTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DamageTask.hpp>
#include <Rosetta/PlayMode/Actions/Draw.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/CustomTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DamageNumberTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ConditionTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FlagTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawMinionTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawSpellTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawRaceMinionTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DestroyTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FreezeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/IncludeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FilterStackTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/RandomTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ReturnHandTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/HealTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/GetGameTagTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/EnqueueTask.hpp>
#include <Rosetta/PlayMode/Tasks/ComplexTask.hpp>
#include <Rosetta/PlayMode/Enchants/Effects.hpp>
#include <Rosetta/PlayMode/Auras/Aura.hpp>
#include <Rosetta/PlayMode/Enchants/Enchant.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SetGameTagTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SilenceTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SummonTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/WeaponTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ManaCrystalTask.hpp>

#include <stdexcept>
#include <algorithm>
#include <memory>
#include <utility>

namespace RosettaStone::PlayMode
{
void ManaMindEffectCompositionGen::AddAll(std::map<std::string, CardDef>& cards)
{
using namespace SimpleTasks;

    if (cards.contains("EDR_468e"))
        throw std::logic_error("duplicate generated CardDef: EDR_468e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackN(4) }));
        cards.emplace("EDR_468e", std::move(enchantDef));
    }

    if (cards.contains("END_014e"))
        throw std::logic_error("duplicate generated CardDef: END_014e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(3) }));
        cards.emplace("END_014e", std::move(enchantDef));
    }

    if (cards.contains("JAIL_376e"))
        throw std::logic_error("duplicate generated CardDef: JAIL_376e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackN(1), Effects::HealthN(2) }));
        cards.emplace("JAIL_376e", std::move(enchantDef));
    }

    if (cards.contains("EDR_572e"))
        throw std::logic_error("duplicate generated CardDef: EDR_572e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::ReduceCost(1) }));
        cards.emplace("EDR_572e", std::move(enchantDef));
    }

    if (cards.contains("ICC_210e"))
        throw std::logic_error("duplicate generated CardDef: ICC_210e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(1) }));
        cards.emplace("ICC_210e", std::move(enchantDef));
    }

    if (cards.contains("CATA_467e"))
        throw std::logic_error("duplicate generated CardDef: CATA_467e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackN(2) }));
        cards.emplace("CATA_467e", std::move(enchantDef));
    }

    if (cards.contains("CORE_DRG_403e"))
        throw std::logic_error("duplicate generated CardDef: CORE_DRG_403e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddAura(std::make_shared<Aura>(
            AuraType::ENEMY_HERO_POWER, EffectList{ Effects::SetCost(2) }));
        const auto aura = dynamic_cast<Aura*>(enchantDef.power.GetAura());
        aura->removeTrigger = { TriggerType::INSPIRE, nullptr };
        cards.emplace("CORE_DRG_403e", std::move(enchantDef));
    }

    if (cards.contains("CATA_305e"))
        throw std::logic_error("duplicate generated CardDef: CATA_305e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::HealthN(3) }));
        cards.emplace("CATA_305e", std::move(enchantDef));
    }

    if (cards.contains("CORE_WW_329e"))
        throw std::logic_error("duplicate generated CardDef: CORE_WW_329e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(2) }));
        cards.emplace("CORE_WW_329e", std::move(enchantDef));
    }

    if (cards.contains("TIME_037e"))
        throw std::logic_error("duplicate generated CardDef: TIME_037e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::HealthN(2) }));
        cards.emplace("TIME_037e", std::move(enchantDef));
    }

    if (cards.contains("JAIL_387e"))
        throw std::logic_error("duplicate generated CardDef: JAIL_387e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackN(2), Effects::HealthN(1) }));
        cards.emplace("JAIL_387e", std::move(enchantDef));
    }

    if (cards.contains("TLC_828e"))
        throw std::logic_error("duplicate generated CardDef: TLC_828e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(2) }));
        cards.emplace("TLC_828e", std::move(enchantDef));
    }

    if (cards.contains("END_021e"))
        throw std::logic_error("duplicate generated CardDef: END_021e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackN(2) }));
        cards.emplace("END_021e", std::move(enchantDef));
    }

    if (cards.contains("MEND_305e"))
        throw std::logic_error("duplicate generated CardDef: MEND_305e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(2) }));
        cards.emplace("MEND_305e", std::move(enchantDef));
    }

    if (cards.contains("DINO_419e"))
        throw std::logic_error("duplicate generated CardDef: DINO_419e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(2) }));
        cards.emplace("DINO_419e", std::move(enchantDef));
    }

    if (cards.contains("TLC_623e"))
        throw std::logic_error("duplicate generated CardDef: TLC_623e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::AttackHealthN(2) }));
        cards.emplace("TLC_623e", std::move(enchantDef));
    }

    if (cards.contains("CATA_458e"))
        throw std::logic_error("duplicate generated CardDef: CATA_458e");
    {
        CardDef enchantDef;
        enchantDef.ClearData();
        enchantDef.power.AddEnchant(std::make_shared<Enchant>(
            std::vector<std::shared_ptr<IEffect>>{ Effects::SpellPowerN(1) }));
        cards.emplace("CATA_458e", std::move(enchantDef));
    }

    if (cards.contains("CAP_801"))
        throw std::logic_error("duplicate generated CardDef: CAP_801");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("CS2_009e", EntityType::TARGET));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::TARGET, GameTag::REBORN, 1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("CAP_801", std::move(cardDef));
    }

    if (cards.contains("CATA_304"))
        throw std::logic_error("duplicate generated CardDef: CATA_304");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::SOURCE, 4, false));
        cards.emplace("CATA_304", std::move(cardDef));
    }

    if (cards.contains("CATA_475"))
        throw std::logic_error("duplicate generated CardDef: CATA_475");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<DamageTask>(EntityType::ENEMIES, 2, false) };
        cards.emplace("CATA_475", std::move(cardDef));
    }

    if (cards.contains("CATA_485"))
        throw std::logic_error("duplicate generated CardDef: CATA_485");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 2, true));
        cardDef.power.AddPowerTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMY_MINIONS, 1, 1, true), 1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 } };
        cards.emplace("CATA_485", std::move(cardDef));
    }

    if (cards.contains("CATA_612"))
        throw std::logic_error("duplicate generated CardDef: CATA_612");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<FreezeTask>(EntityType::SOURCE));
        cards.emplace("CATA_612", std::move(cardDef));
    }

    if (cards.contains("DINO_132"))
        throw std::logic_error("duplicate generated CardDef: DINO_132");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMY_MINIONS, 1, 5, false), 1) };
        cards.emplace("DINO_132", std::move(cardDef));
    }

    if (cards.contains("CORE_RLK_083"))
        throw std::logic_error("duplicate generated CardDef: CORE_RLK_083");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_CAST));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::FRIENDLY;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 1, false), 2) };
        cards.emplace("CORE_RLK_083", std::move(cardDef));
    }

    if (cards.contains("END_026"))
        throw std::logic_error("duplicate generated CardDef: END_026");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_CAST));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::FRIENDLY;
        cardDef.power.GetTrigger()->conditions = SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsSpellTargetingMinion()) };
        cardDef.power.GetTrigger()->tasks = { std::make_shared<DrawTask>(1) };
        cards.emplace("END_026", std::move(cardDef));
    }

    if (cards.contains("TLC_256"))
        throw std::logic_error("duplicate generated CardDef: TLC_256");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_CAST));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::FRIENDLY;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::DIVINE_SHIELD, 1) };
        cards.emplace("TLC_256", std::move(cardDef));
    }

    if (cards.contains("CORE_BOT_222"))
        throw std::logic_error("duplicate generated CardDef: CORE_BOT_222");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 4, true));
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::HERO, 4, true));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("CORE_BOT_222", std::move(cardDef));
    }

    if (cards.contains("CORE_BOT_451"))
        throw std::logic_error("duplicate generated CardDef: CORE_BOT_451");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("BOT_102t", 2));
        cards.emplace("CORE_BOT_451", std::move(cardDef));
    }

    if (cards.contains("CORE_CFM_604"))
        throw std::logic_error("duplicate generated CardDef: CORE_CFM_604");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<HealTask>(EntityType::TARGET, 12));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_FRIENDLY_TARGET, 0 } };
        cards.emplace("CORE_CFM_604", std::move(cardDef));
    }

    if (cards.contains("CORE_CS2_004"))
        throw std::logic_error("duplicate generated CardDef: CORE_CS2_004");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("CS2_004e", EntityType::TARGET));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("CORE_CS2_004", std::move(cardDef));
    }

    if (cards.contains("CORE_CS2_024"))
        throw std::logic_error("duplicate generated CardDef: CORE_CS2_024");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 3, true));
        cardDef.power.AddPowerTask(std::make_shared<FreezeTask>(EntityType::TARGET));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 } };
        cards.emplace("CORE_CS2_024", std::move(cardDef));
    }

    if (cards.contains("CORE_CS2_094"))
        throw std::logic_error("duplicate generated CardDef: CORE_CS2_094");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 3, true));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 } };
        cards.emplace("CORE_CS2_094", std::move(cardDef));
    }

    if (cards.contains("CORE_EX1_129"))
        throw std::logic_error("duplicate generated CardDef: CORE_EX1_129");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::ENEMY_MINIONS, 1, true));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cards.emplace("CORE_EX1_129", std::move(cardDef));
    }

    if (cards.contains("CORE_GVG_061"))
        throw std::logic_error("duplicate generated CardDef: CORE_GVG_061");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("CS2_101t", 3));
        cardDef.power.AddPowerTask(std::make_shared<WeaponTask>("CS2_091"));
        cards.emplace("CORE_GVG_061", std::move(cardDef));
    }

    if (cards.contains("CORE_LOOT_013"))
        throw std::logic_error("duplicate generated CardDef: CORE_LOOT_013");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::HERO, 2, false));
        cards.emplace("CORE_LOOT_013", std::move(cardDef));
    }

    if (cards.contains("CORE_LOOT_368"))
        throw std::logic_error("duplicate generated CardDef: CORE_LOOT_368");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<SummonTask>("CS2_065", 3));
        cards.emplace("CORE_LOOT_368", std::move(cardDef));
    }

    if (cards.contains("CORE_OG_031"))
        throw std::logic_error("duplicate generated CardDef: CORE_OG_031");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<SummonTask>("OG_031a", 1));
        cards.emplace("CORE_OG_031", std::move(cardDef));
    }

    if (cards.contains("CORE_OG_149"))
        throw std::logic_error("duplicate generated CardDef: CORE_OG_149");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::ALL_MINIONS_NOSOURCE, 1, false));
        cards.emplace("CORE_OG_149", std::move(cardDef));
    }

    if (cards.contains("CORE_RLK_062"))
        throw std::logic_error("duplicate generated CardDef: CORE_RLK_062");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("CORE_RLK_062", 2));
        cards.emplace("CORE_RLK_062", std::move(cardDef));
    }

    if (cards.contains("CORE_SW_066"))
        throw std::logic_error("duplicate generated CardDef: CORE_SW_066");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SilenceTask>(EntityType::TARGET));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("CORE_SW_066", std::move(cardDef));
    }

    if (cards.contains("CORE_TSC_076"))
        throw std::logic_error("duplicate generated CardDef: CORE_TSC_076");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("TSC_076t3", 1));
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("TSC_076t2", 1));
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("TSC_076t", 1));
        cards.emplace("CORE_TSC_076", std::move(cardDef));
    }

    if (cards.contains("CORE_UNG_084"))
        throw std::logic_error("duplicate generated CardDef: CORE_UNG_084");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 3, false));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_IF_AVAILABLE, 0 }, { PlayReq::REQ_NONSELF_TARGET, 0 } };
        cards.emplace("CORE_UNG_084", std::move(cardDef));
    }

    if (cards.contains("CORE_YOP_034"))
        throw std::logic_error("duplicate generated CardDef: CORE_YOP_034");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMY_MINIONS, 1, 10, false), 1) };
        cards.emplace("CORE_YOP_034", std::move(cardDef));
    }

    if (cards.contains("EDR_110"))
        throw std::logic_error("duplicate generated CardDef: EDR_110");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMY_MINIONS, 1, 1, false), 1));
        cards.emplace("EDR_110", std::move(cardDef));
    }

    if (cards.contains("EDR_459"))
        throw std::logic_error("duplicate generated CardDef: EDR_459");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::MINIONS_NOSOURCE, 3, false));
        cardDef.power.AddDeathrattleTask(std::make_shared<DamageTask>(EntityType::ENEMY_MINIONS, 3, false));
        cards.emplace("EDR_459", std::move(cardDef));
    }

    if (cards.contains("EDR_476"))
        throw std::logic_error("duplicate generated CardDef: EDR_476");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::ENEMIES, 4, true));
        cardDef.power.AddPowerTask(std::make_shared<HealTask>(EntityType::FRIENDS, 4));
        cards.emplace("EDR_476", std::move(cardDef));
    }

    if (cards.contains("EDR_971"))
        throw std::logic_error("duplicate generated CardDef: EDR_971");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<HealTask>(EntityType::HEROES, 3) };
        cards.emplace("EDR_971", std::move(cardDef));
    }

    if (cards.contains("END_007"))
        throw std::logic_error("duplicate generated CardDef: END_007");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 1, true));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("BTA_02pe", EntityType::HERO));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.power.AddPowerTask(std::make_shared<ArmorTask>(1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 } };
        cards.emplace("END_007", std::move(cardDef));
    }

    if (cards.contains("FIR_778"))
        throw std::logic_error("duplicate generated CardDef: FIR_778");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DamageTask>(EntityType::ENEMY_MINIONS, 9, false));
        cards.emplace("FIR_778", std::move(cardDef));
    }

    if (cards.contains("FIR_909"))
        throw std::logic_error("duplicate generated CardDef: FIR_909");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 2, true), 3));
        cards.emplace("FIR_909", std::move(cardDef));
    }

    if (cards.contains("JAIL_007"))
        throw std::logic_error("duplicate generated CardDef: JAIL_007");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DamageTask>(EntityType::ENEMY_MINIONS, 2, false));
        cardDef.power.AddDeathrattleTask(std::make_shared<DamageTask>(EntityType::ENEMY_HERO, 2, false));
        cards.emplace("JAIL_007", std::move(cardDef));
    }

    if (cards.contains("RLK_024"))
        throw std::logic_error("duplicate generated CardDef: RLK_024");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 6, false));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("RLK_024", std::move(cardDef));
    }

    if (cards.contains("RLK_709"))
        throw std::logic_error("duplicate generated CardDef: RLK_709");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::ENEMIES, 2, true));
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cards.emplace("RLK_709", std::move(cardDef));
    }

    if (cards.contains("TIME_215"))
        throw std::logic_error("duplicate generated CardDef: TIME_215");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::ALL_MINIONS_NOSOURCE, 1, true));
        cardDef.power.AddPowerTask(std::make_shared<AddCardTask>(EntityType::HAND, "TIME_218", 1));
        cards.emplace("TIME_215", std::move(cardDef));
    }

    if (cards.contains("TIME_218"))
        throw std::logic_error("duplicate generated CardDef: TIME_218");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 1, true));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("BTA_02pe", EntityType::HERO));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("TIME_218", std::move(cardDef));
    }

    if (cards.contains("TLC_225"))
        throw std::logic_error("duplicate generated CardDef: TLC_225");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<SummonTask>("TLC_249", 1));
        cards.emplace("TLC_225", std::move(cardDef));
    }

    if (cards.contains("TLC_249"))
        throw std::logic_error("duplicate generated CardDef: TLC_249");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 1), 2));
        cards.emplace("TLC_249", std::move(cardDef));
    }

    if (cards.contains("TLC_620"))
        throw std::logic_error("duplicate generated CardDef: TLC_620");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ArmorTask>(3));
        cardDef.power.AddPowerTask(std::make_shared<GetGameTagTask>(EntityType::HERO, GameTag::ARMOR));
        cardDef.power.AddPowerTask(std::make_shared<DamageNumberTask>(EntityType::TARGET, true));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_ENEMY_TARGET, 0 } };
        cards.emplace("TLC_620", std::move(cardDef));
    }

    if (cards.contains("TIME_015"))
        throw std::logic_error("duplicate generated CardDef: TIME_015");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<HealTask>(EntityType::HERO, 3));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::HERO, GameTag::DIVINE_SHIELD, 1));
        cards.emplace("TIME_015", std::move(cardDef));
    }

    if (cards.contains("TLC_401"))
        throw std::logic_error("duplicate generated CardDef: TLC_401");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 6, false), 3));
        cards.emplace("TLC_401", std::move(cardDef));
    }

    if (cards.contains("RLK_223"))
        throw std::logic_error("duplicate generated CardDef: RLK_223");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 2, false), 1));
        cardDef.power.AddDeathrattleTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMIES, 1, 2, false), 1));
        cards.emplace("RLK_223", std::move(cardDef));
    }

    if (cards.contains("CORE_ICC_210"))
        throw std::logic_error("duplicate generated CardDef: CORE_ICC_210");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<RandomTask>(EntityType::STACK, 1), std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK) };
        cards.emplace("CORE_ICC_210", std::move(cardDef));
    }

    if (cards.contains("CORE_AT_062"))
        throw std::logic_error("duplicate generated CardDef: CORE_AT_062");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("FP1_011", 3));
        cards.emplace("CORE_AT_062", std::move(cardDef));
    }

    if (cards.contains("EDR_942"))
        throw std::logic_error("duplicate generated CardDef: EDR_942");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<SetGameTagTask>(EntityType::HERO, GameTag::DIVINE_SHIELD, 1) };
        cards.emplace("EDR_942", std::move(cardDef));
    }

    if (cards.contains("TIME_100"))
        throw std::logic_error("duplicate generated CardDef: TIME_100");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(nullptr);
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::MINIONS_HAND) };
        cards.emplace("TIME_100", std::move(cardDef));
    }

    if (cards.contains("EDR_889"))
        throw std::logic_error("duplicate generated CardDef: EDR_889");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsRace(Race::DRAGON)) }), std::make_shared<RandomTask>(EntityType::STACK, 1), std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK) };
        cards.emplace("EDR_889", std::move(cardDef));
    }

    if (cards.contains("CORE_GVG_059"))
        throw std::logic_error("duplicate generated CardDef: CORE_GVG_059");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS));
        cardDef.power.AddPowerTask(std::make_shared<RandomTask>(EntityType::STACK, 1));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::STACK, GameTag::DIVINE_SHIELD, 1));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::STACK, GameTag::TAUNT, 1));
        cards.emplace("CORE_GVG_059", std::move(cardDef));
    }

    if (cards.contains("CORE_ICC_214"))
        throw std::logic_error("duplicate generated CardDef: CORE_ICC_214");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<IncludeTask>(EntityType::ENEMY_MINIONS));
        cardDef.power.AddDeathrattleTask(std::make_shared<RandomTask>(EntityType::STACK, 1));
        cardDef.power.AddDeathrattleTask(std::make_shared<DestroyTask>(EntityType::STACK));
        cards.emplace("CORE_ICC_214", std::move(cardDef));
    }

    if (cards.contains("TLC_EVENT_402"))
        throw std::logic_error("duplicate generated CardDef: TLC_EVENT_402");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DestroyTask>(EntityType::ALL_MINIONS));
        cards.emplace("TLC_EVENT_402", std::move(cardDef));
    }

    if (cards.contains("CORE_KAR_061"))
        throw std::logic_error("duplicate generated CardDef: CORE_KAR_061");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawRaceMinionTask>(Race::BEAST, 1, false));
        cardDef.power.AddPowerTask(std::make_shared<DrawRaceMinionTask>(Race::DRAGON, 1, false));
        cardDef.power.AddPowerTask(std::make_shared<DrawRaceMinionTask>(Race::MURLOC, 1, false));
        cards.emplace("CORE_KAR_061", std::move(cardDef));
    }

    if (cards.contains("CORE_GVG_103"))
        throw std::logic_error("duplicate generated CardDef: CORE_GVG_103");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_START));
        cardDef.power.GetTrigger()->eitherTurn = true;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<AddEnchantmentTask>("EX1_162o", EntityType::SOURCE) };
        cards.emplace("CORE_GVG_103", std::move(cardDef));
    }

    if (cards.contains("EDR_816"))
        throw std::logic_error("duplicate generated CardDef: EDR_816");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<AddEnchantmentTask>("EX1_162o", EntityType::STACK) };
        cards.emplace("EDR_816", std::move(cardDef));
    }

    if (cards.contains("TIME_428"))
        throw std::logic_error("duplicate generated CardDef: TIME_428");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<AddEnchantmentTask>("DRG_057e", EntityType::STACK) };
        cards.emplace("TIME_428", std::move(cardDef));
    }

    if (cards.contains("CORE_OG_211"))
        throw std::logic_error("duplicate generated CardDef: CORE_OG_211");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("NEW1_032", 1));
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("NEW1_033", 1));
        cardDef.power.AddPowerTask(std::make_shared<SummonTask>("NEW1_034", 1));
        cards.emplace("CORE_OG_211", std::move(cardDef));
    }

    if (cards.contains("CORE_GIL_534"))
        throw std::logic_error("duplicate generated CardDef: CORE_GIL_534");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::SOURCE) };
        cards.emplace("CORE_GIL_534", std::move(cardDef));
    }

    if (cards.contains("JAIL_329"))
        throw std::logic_error("duplicate generated CardDef: JAIL_329");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS), std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { return playable->card->GetCardClass() == CardClass::PALADIN; }) }), std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK), std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK) };
        cards.emplace("JAIL_329", std::move(cardDef));
    }

    if (cards.contains("TIME_212"))
        throw std::logic_error("duplicate generated CardDef: TIME_212");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 2, true));
        cardDef.power.AddPowerTask(std::make_shared<EnqueueTask>(ComplexTask::DamageRandomTargets(EntityType::ENEMY_MINIONS, 1, 4, true), 1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_FRIENDLY_TARGET, 0 } };
        cards.emplace("TIME_212", std::move(cardDef));
    }

    if (cards.contains("DINO_406"))
        throw std::logic_error("duplicate generated CardDef: DINO_406");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 4, true));
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsRace(Race::ELEMENTAL)) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 } };
        cards.emplace("DINO_406", std::move(cardDef));
    }

    if (cards.contains("CATA_201"))
        throw std::logic_error("duplicate generated CardDef: CATA_201");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ReturnHandTask>(EntityType::ENEMY_MINIONS));
        cards.emplace("CATA_201", std::move(cardDef));
    }

    if (cards.contains("JAIL_441"))
        throw std::logic_error("duplicate generated CardDef: JAIL_441");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 3, true));
        cardDef.power.AddPowerTask(std::make_shared<CustomTask>([](Player* player, Entity*, Playable*) { player->GetHeroPower().SetExhausted(false); }));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("JAIL_441", std::move(cardDef));
    }

    if (cards.contains("CATA_203"))
        throw std::logic_error("duplicate generated CardDef: CATA_203");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DestroyTask>(EntityType::TARGET));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_LEGENDARY_TARGET, 0 } };
        cards.emplace("CATA_203", std::move(cardDef));
    }

    if (cards.contains("EDR_485"))
        throw std::logic_error("duplicate generated CardDef: EDR_485");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawMinionTask>(DrawMinionType::MIN_COST_AT_LEAST, 1, false, 7));
        cards.emplace("EDR_485", std::move(cardDef));
    }

    if (cards.contains("EDR_571"))
        throw std::logic_error("duplicate generated CardDef: EDR_571");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawSpellTask>(SpellSchool::NONE, DrawSpellType::MIN_COST_AT_LEAST, 1, false, 5));
        cards.emplace("EDR_571", std::move(cardDef));
    }

    if (cards.contains("FIR_954"))
        throw std::logic_error("duplicate generated CardDef: FIR_954");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 5, true));
        cardDef.power.AddPowerTask(std::make_shared<CustomTask>([](Player*, Entity*, Playable* target) { if (target && target->player) Generic::Draw(target->player, nullptr); }));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("FIR_954", std::move(cardDef));
    }

    if (cards.contains("CATA_467"))
        throw std::logic_error("duplicate generated CardDef: CATA_467");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::AFTER_ATTACK));
        cardDef.power.GetTrigger()->triggerSource = TriggerSource::HERO;
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<RandomTask>(EntityType::STACK, 1), std::make_shared<AddEnchantmentTask>("CATA_467e", EntityType::STACK) };
        cards.emplace("CATA_467", std::move(cardDef));
    }

    if (cards.contains("CORE_DRG_403"))
        throw std::logic_error("duplicate generated CardDef: CORE_DRG_403");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("CORE_DRG_403e", EntityType::ENEMY_PLAYER));
        cards.emplace("CORE_DRG_403", std::move(cardDef));
    }

    if (cards.contains("CATA_305"))
        throw std::logic_error("duplicate generated CardDef: CATA_305");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->conditions = SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsUndamaged()) };
        cardDef.power.GetTrigger()->tasks = { std::make_shared<AddEnchantmentTask>("CATA_305e", EntityType::SOURCE) };
        cards.emplace("CATA_305", std::move(cardDef));
    }

    if (cards.contains("CORE_CFM_753"))
        throw std::logic_error("duplicate generated CardDef: CORE_CFM_753");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::MINIONS_HAND));
        cards.emplace("CORE_CFM_753", std::move(cardDef));
    }

    if (cards.contains("CORE_WW_329"))
        throw std::logic_error("duplicate generated CardDef: CORE_WW_329");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_HAND));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsTagValue(GameTag::TAUNT, 1)) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("CORE_WW_329e", EntityType::STACK));
        cards.emplace("CORE_WW_329", std::move(cardDef));
    }

    if (cards.contains("TIME_037"))
        throw std::logic_error("duplicate generated CardDef: TIME_037");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawMinionTask>(DrawMinionType::DEFAULT, 1, false));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("TIME_037e", EntityType::MINIONS_HAND));
        cards.emplace("TIME_037", std::move(cardDef));
    }

    if (cards.contains("JAIL_387"))
        throw std::logic_error("duplicate generated CardDef: JAIL_387");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::MINIONS_HAND));
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_HAND));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { return playable->card->GetRarity() == Rarity::LEGENDARY; }) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("JAIL_387e", EntityType::STACK));
        cards.emplace("JAIL_387", std::move(cardDef));
    }

    if (cards.contains("TLC_828"))
        throw std::logic_error("duplicate generated CardDef: TLC_828");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_HAND_DECK_FIELD));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsRace(Race::BEAST)) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("TLC_828e", EntityType::STACK));
        cards.emplace("TLC_828", std::move(cardDef));
    }

    if (cards.contains("END_021"))
        throw std::logic_error("duplicate generated CardDef: END_021");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::HAND));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { const auto type = playable->card->GetCardType(); return type == CardType::MINION || type == CardType::WEAPON; }) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("END_021e", EntityType::STACK));
        cards.emplace("END_021", std::move(cardDef));
    }

    if (cards.contains("MEND_305"))
        throw std::logic_error("duplicate generated CardDef: MEND_305");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("MEND_305e", EntityType::TARGET));
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_HAND));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsRace(Race::BEAST)) }));
        cardDef.power.AddPowerTask(std::make_shared<RandomTask>(EntityType::STACK, 1));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("MEND_305e", EntityType::STACK));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_FRIENDLY_TARGET, 0 }, { PlayReq::REQ_TARGET_WITH_RACE, 20 } };
        cards.emplace("MEND_305", std::move(cardDef));
    }

    if (cards.contains("DINO_419"))
        throw std::logic_error("duplicate generated CardDef: DINO_419");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("DINO_419e", EntityType::TARGET));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::TARGET, GameTag::RUSH, 1));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_FRIENDLY_TARGET, 0 }, { PlayReq::REQ_TARGET_WITH_RACE, 20 } };
        cards.emplace("DINO_419", std::move(cardDef));
    }

    if (cards.contains("EDR_861"))
        throw std::logic_error("duplicate generated CardDef: EDR_861");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<ManaCrystalTask>(1, false));
        cardDef.power.AddDeathrattleTask(std::make_shared<ManaCrystalTask>(1, false, true));
        cards.emplace("EDR_861", std::move(cardDef));
    }

    if (cards.contains("TLC_621"))
        throw std::logic_error("duplicate generated CardDef: TLC_621");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<CustomTask>([](Player* player, Entity*, Playable*) { for (int i = 0; i < 3; ++i) { auto* top = player->GetDeckZone()->GetTopCard(); if (!top) break; top->Destroy(); } }));
        cards.emplace("TLC_621", std::move(cardDef));
    }

    if (cards.contains("TLC_623"))
        throw std::logic_error("duplicate generated CardDef: TLC_623");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddTrigger(std::make_shared<Trigger>(TriggerType::TURN_END));
        cardDef.power.GetTrigger()->tasks = { std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE), std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsDamaged()) }), std::make_shared<RandomTask>(EntityType::STACK, 1), std::make_shared<AddEnchantmentTask>("TLC_623e", EntityType::STACK) };
        cards.emplace("TLC_623", std::move(cardDef));
    }

    if (cards.contains("CATA_458"))
        throw std::logic_error("duplicate generated CardDef: CATA_458");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::HAND_SPELL));
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::DECK));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { return playable->card->GetCardType() == CardType::SPELL; }) }));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("CATA_458e", EntityType::STACK));
        cards.emplace("CATA_458", std::move(cardDef));
    }

    if (cards.contains("JAIL_377"))
        throw std::logic_error("duplicate generated CardDef: JAIL_377");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1, true));
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::STACK, SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsCost(2, RelaSign::LEQ)) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<DrawTask>(1) }));
        cards.emplace("JAIL_377", std::move(cardDef));
    }

    if (cards.contains("JAIL_456"))
        throw std::logic_error("duplicate generated CardDef: JAIL_456");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::SOURCE, SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { return playable->player->GetDeckZone()->GetCount() >= 25; }) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<DrawTask>(1) }));
        cards.emplace("JAIL_456", std::move(cardDef));
    }

    if (cards.contains("CATA_303"))
        throw std::logic_error("duplicate generated CardDef: CATA_303");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 5, true));
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::TARGET, SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsDead()) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<HealTask>(EntityType::ENEMY_HERO, 5) }));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("CATA_303", std::move(cardDef));
    }

    if (cards.contains("END_014"))
        throw std::logic_error("duplicate generated CardDef: END_014");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 3, true));
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::TARGET, SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsDead()) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<IncludeTask>(EntityType::MINIONS), std::make_shared<RandomTask>(EntityType::STACK, 1), std::make_shared<AddEnchantmentTask>("END_014e", EntityType::STACK) }));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_NONSELF_TARGET, 0 } };
        cards.emplace("END_014", std::move(cardDef));
    }

    if (cards.contains("TLC_606"))
        throw std::logic_error("duplicate generated CardDef: TLC_606");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 2, false));
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::TARGET, SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsDead()) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<ArmorTask>(5) }));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_ENEMY_TARGET, 0 } };
        cards.emplace("TLC_606", std::move(cardDef));
    }

    if (cards.contains("EDR_468"))
        throw std::logic_error("duplicate generated CardDef: EDR_468");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 1, false));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("EDR_468e", EntityType::TARGET));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 } };
        cards.emplace("EDR_468", std::move(cardDef));
    }

    if (cards.contains("JAIL_376"))
        throw std::logic_error("duplicate generated CardDef: JAIL_376");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<IncludeTask>(EntityType::MINIONS));
        cardDef.power.AddDeathrattleTask(std::make_shared<FilterStackTask>(SelfCondList{ std::make_shared<SelfCondition>(SelfCondition::IsDamaged()) }));
        cardDef.power.AddDeathrattleTask(std::make_shared<AddEnchantmentTask>("JAIL_376e", EntityType::STACK));
        cards.emplace("JAIL_376", std::move(cardDef));
    }

    if (cards.contains("JAIL_462"))
        throw std::logic_error("duplicate generated CardDef: JAIL_462");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(2, true));
        cardDef.power.AddPowerTask(std::make_shared<ConditionTask>(EntityType::SOURCE, SelfCondList{ std::make_shared<SelfCondition>([](Playable* playable) { const auto& drawn = playable->player->game->taskStack.playables; return drawn.size() == 2 && std::all_of(drawn.begin(), drawn.end(), [](Playable* card) { return card && card->card->GetCardType() == CardType::MINION; }); }) }));
        cardDef.power.AddPowerTask(std::make_shared<FlagTask>(true, TaskList{ std::make_shared<SetGameTagTask>(EntityType::SOURCE, GameTag::CHARGE, 1) }));
        cards.emplace("JAIL_462", std::move(cardDef));
    }

    if (cards.contains("EDR_572"))
        throw std::logic_error("duplicate generated CardDef: EDR_572");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawRaceMinionTask>(Race::DRAGON, 2, true));
        cardDef.power.AddDeathrattleTask(std::make_shared<AddEnchantmentTask>("EDR_572e", EntityType::STACK));
        cards.emplace("EDR_572", std::move(cardDef));
    }

    if (cards.contains("TLC_633"))
        throw std::logic_error("duplicate generated CardDef: TLC_633");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DamageTask>(EntityType::TARGET, 6, false));
        cardDef.property.playReqs = PlayReqs{ { PlayReq::REQ_TARGET_TO_PLAY, 0 }, { PlayReq::REQ_MINION_TARGET, 0 }, { PlayReq::REQ_ENEMY_TARGET, 0 }, { PlayReq::REQ_TARGET_WITH_RACE, static_cast<int>(Race::ALL) } };
        cards.emplace("TLC_633", std::move(cardDef));
    }
}
}  // namespace RosettaStone::PlayMode
