// Generated by scripts/generate_minion_set_enchant.py. Do not edit.
#include <Rosetta/PlayMode/CardSets/ManaMindMinionSetEnchantGen.hpp>
#include <Rosetta/PlayMode/Conditions/SelfCondition.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/IncludeTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/FilterStackTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/AddEnchantmentTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/SetGameTagTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode {
void ManaMindMinionSetEnchantGen::AddAll(std::map<std::string, CardDef>& cards) {
    using namespace SimpleTasks;
    if (cards.contains("RLK_048")) throw std::logic_error("duplicate generated CardDef: RLK_048");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::STACK, GameTag::CANT_BE_TARGETED_BY_SPELLS, 1));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::STACK, GameTag::CANT_BE_TARGETED_BY_HERO_POWERS, 1));
        cards.emplace("RLK_048", std::move(cardDef));
    }

    if (cards.contains("TIME_447")) throw std::logic_error("duplicate generated CardDef: TIME_447");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.property.playReqs.emplace(PlayReq::REQ_TARGET_TO_PLAY, 0);
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::TARGET, GameTag::DIVINE_SHIELD, 1));
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_HAND));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ULD_191e", EntityType::STACK));
        cards.emplace("TIME_447", std::move(cardDef));
    }

    if (cards.contains("TLC_233")) throw std::logic_error("duplicate generated CardDef: TLC_233");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<IncludeTask>(EntityType::MINIONS_NOSOURCE));
        cardDef.power.AddPowerTask(std::make_shared<FilterStackTask>(std::vector<std::shared_ptr<SelfCondition>>{std::make_shared<SelfCondition>(SelfCondition::IsAttack(2, RelaSign::LEQ))}));
        cardDef.power.AddPowerTask(std::make_shared<AddEnchantmentTask>("ICC_210e", EntityType::STACK));
        cardDef.power.AddPowerTask(std::make_shared<SetGameTagTask>(EntityType::STACK, GameTag::TAUNT, 1));
        cards.emplace("TLC_233", std::move(cardDef));
    }
}
}
