// Generated by scripts/generate_repeated_trigger_draw.py. Do not edit by hand.
#include <Rosetta/PlayMode/CardSets/ManaMindRepeatedTriggerDrawGen.hpp>
#include <Rosetta/PlayMode/Cards/CardPowers.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawOpTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/DrawTask.hpp>
#include <Rosetta/PlayMode/Tasks/SimpleTasks/ArmorTask.hpp>
#include <memory>
#include <stdexcept>
#include <utility>
namespace RosettaStone::PlayMode
{
void ManaMindRepeatedTriggerDrawGen::AddAll(std::map<std::string, CardDef>& cards)
{
using namespace SimpleTasks;

    if (cards.contains("CORE_DMF_067"))
        throw std::logic_error("duplicate generated CardDef: CORE_DMF_067");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.power.AddPowerTask(std::make_shared<DrawOpTask>(1));
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawTask>(1));
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawOpTask>(1));
        cards.emplace("CORE_DMF_067", std::move(cardDef));
    }

    if (cards.contains("RLK_708"))
        throw std::logic_error("duplicate generated CardDef: RLK_708");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<DrawTask>(1));
        cardDef.power.AddDeathrattleTask(std::make_shared<DrawTask>(1));
        cards.emplace("RLK_708", std::move(cardDef));
    }

    if (cards.contains("CORE_RLK_657"))
        throw std::logic_error("duplicate generated CardDef: CORE_RLK_657");
    {
        CardDef cardDef;
        cardDef.ClearData();
        cardDef.power.AddPowerTask(std::make_shared<ArmorTask>(6));
        cardDef.power.AddDeathrattleTask(std::make_shared<ArmorTask>(6));
        cards.emplace("CORE_RLK_657", std::move(cardDef));
    }
}
}  // namespace RosettaStone::PlayMode
