// Generated by scripts/generate_after_attack_draw.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_AFTER_ATTACK_DRAW_CARDS_GEN_HPP
#define ROSETTASTONE_MANAMIND_AFTER_ATTACK_DRAW_CARDS_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode
{
class ManaMindAfterAttackDrawCardsGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode
#endif  // ROSETTASTONE_MANAMIND_AFTER_ATTACK_DRAW_CARDS_GEN_HPP
