// Generated by scripts/generate_metadata_only_cards.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_METADATA_ONLY_CARDS_GEN_HPP
#define ROSETTASTONE_MANAMIND_METADATA_ONLY_CARDS_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode { class ManaMindMetadataOnlyCardsGen { public: static void AddAll(std::map<std::string, CardDef>& cards); }; }
#endif
