// Generated by scripts/generate_profile_deck_minion_cost_summon.py. Do not edit.
#pragma once
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode {
class ManaMindProfileDeckMinionCostSummonGen {
 public: static void AddAll(std::map<std::string, CardDef>& cards);
};
}
