// Generated by scripts/generate_held_card_gate_fixed_battlecry.py. Do not edit.
#pragma once
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode {
class ManaMindHeldCardGateFixedBattlecryGen { public: static void AddAll(std::map<std::string, CardDef>& cards); };
}
