// Generated by scripts/generate_effect_composition.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
#define ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode
{
class ManaMindEffectCompositionGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode
#endif  // ROSETTASTONE_MANAMIND_EFFECT_COMPOSITION_GEN_HPP
