// Generated by scripts/generate_minion_set_enchant.py. Do not edit.
#pragma once
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode {
class ManaMindMinionSetEnchantGen {
 public: static void AddAll(std::map<std::string, CardDef>& cards);
};
}
