// Generated by scripts/generate_core_card_aliases.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_CORE_ALIAS_CARDS_GEN_HPP
#define ROSETTASTONE_MANAMIND_CORE_ALIAS_CARDS_GEN_HPP

#include <Rosetta/PlayMode/Cards/CardDef.hpp>

#include <map>
#include <string>

namespace RosettaStone::PlayMode
{
class ManaMindCoreAliasCardsGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode

#endif  // ROSETTASTONE_MANAMIND_CORE_ALIAS_CARDS_GEN_HPP
