// Generated by scripts/generate_filtered_school_draw.py. Do not edit by hand.
#ifndef ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
#define ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
#include <Rosetta/PlayMode/Cards/CardDef.hpp>
#include <map>
#include <string>
namespace RosettaStone::PlayMode
{
class ManaMindFilteredSchoolDrawGen
{
 public:
    static void AddAll(std::map<std::string, CardDef>& cards);
};
}  // namespace RosettaStone::PlayMode
#endif  // ROSETTASTONE_MANAMIND_FILTERED_SCHOOL_DRAW_GEN_HPP
